In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url = "https://books.toscrape.com/"

In [3]:
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/140.0.0.0 Safari/537.36"
}

response = requests.get(url, headers=headers)

print(response.status_code)

200

In [4]:
soup = BeautifulSoup(response.text, "html.parser")

In [5]:
print(soup.title.text)

    All products | Books to Scrape - Sandbox

In [6]:
books = soup.find_all("article", class_="product_pod")

print(len(books))

20

In [7]:
book = books[0]

title = book.h3.a["title"]

price = book.find("p", class_="price_color").text

print(title)
print(price)

A Light in the Attic
Â£51.77

In [8]:
titles = []
prices = []

for book in books:

    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text

    titles.append(title)
    prices.append(price)

In [9]:
df = pd.DataFrame({
    "Book": titles,
    "Price": prices
})

df

                                                 Book    Price
0                                A Light in the Attic  Â£51.77
1                                  Tipping the Velvet  Â£53.74
2                                          Soumission  Â£50.10
3                                       Sharp Objects  Â£47.82
4               Sapiens: A Brief History of Humankind  Â£54.23
5                                     The Requiem Red  Â£22.65
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60
9                                     The Black Maria  Â£52.15
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99
11                              Shakespeare's Sonnets  Â£20.66
12                                        Set Me Free  Â£17.46
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29
14                          Rip it Up and Start Again  Â£35.02
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25
16                                               Olio  Â£23.88
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59
18                       Libertarianism for Beginners  Â£51.33
19                            It's Only the Himalayas  Â£45.17

In [10]:
stocks = []

for book in books:

    stock = book.find("p", class_="instock availability").text.strip()

    stocks.append(stock)

In [11]:
df["stock"]=stocks

In [12]:
df.head(5)

                                    Book    Price     stock
0                   A Light in the Attic  Â£51.77  In stock
1                     Tipping the Velvet  Â£53.74  In stock
2                             Soumission  Â£50.10  In stock
3                          Sharp Objects  Â£47.82  In stock
4  Sapiens: A Brief History of Humankind  Â£54.23  In stock